# Generated by Django 6.0.5 on 2026-06-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='origin',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
