# Generated by Django 6.0.6 on 2026-07-20 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_itineraryday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_settlement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_received_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
