# Generated by Django 6.0.6 on 2026-07-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_expense_is_settlement_expense_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
